name: Build StorePass Executables

on:
  workflow_dispatch: # Manual trigger only

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller customtkinter cryptography requests

      - name: Clean build executable
        run: |
          pyinstaller --clean --onefile --windowed storepass.py

      - name: Rename executable for OS
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            ren dist\storepass.exe storepass-windows.exe
          elif [ "${{ runner.os }}" == "Linux" ]; then
            mv dist/storepass storepass-linux
          elif [ "${{ runner.os }}" == "macOS" ]; then
            mv dist/storepass storepass-macos
          fi
        shell: bash

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: storepass-${{ matrix.os }}
          path: dist/*

