name: Build StorePass Executables

on:
  workflow_dispatch: # Manual trigger only

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller customtkinter cryptography requests

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed storepass.py

      - name: Rename executable for OS
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv dist/storepass.exe dist/storepass-windows.exe
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            mv dist/storepass dist/storepass-linux
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            mv dist/storepass dist/storepass-macos
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: storepass-${{ matrix.os }}
          path: dist/*

